### PR TITLE
rsp-10: Added Hasura permissions and exposed GraphQL API

### LINKED ISSUE #8: Cannot generate/apply Directus `schema` snapshot in Docker
## References
https://github.com/directus/directus/discussions/16988

### LINKED ISSUE #9: Dockerize Hasura GraphQL Engine
## References
https://hub.docker.com/r/hasura/graphql-engine

### PR DESCRIPTION
**Pull request by e3stpavel**
## Changelog:
* adds permissions (`protected`, `public`)
* adds some minor Kaspar changes in `products` schema
* fixes metadata
* _to ignore_ adds GraphQL queries in `queries.graphql`
* resolves #8 
* fixed #9

### CODE REVIEW

**Comment by e3stpavel** [comment]
@all-contributors please add @e3stpavel for code,doc,bug,design

**Comment by e3stpavel** [comment]
@all-contributors please add @e3stpavel for code,doc,bug,design

**Comment by e3stpavel** [comment]
Thanks @eskozloi for Directus schema. @all-contributors, could you add please @eskozloi for code?

**Comment by e3stpavel** [comment]
Thanks Andrew for Directus schema 🥇 @all-contributors please add @eskozloi for code

**Review by eskozloi — APPROVED** [review]

**Pull request merged**
